### ISSUE TITLE
Frog s are not spawning.

### ISSUE THREAD

**Issue by EredmiR** [frikinjay/morefrogs#11]
All the best. I report that I can't get frogs to spawn in the biomes the wiki says, the only way to do that is to place the frog egg spawn in the biome, but in survival this can't be done. The eggs do not appear to me to appear the frogs. It also doesn't spawn the last frog that spawns too high, and neither does its block, I don't know what to do.

**Comment by frikinjay** [comment]
The frog spawns like vanilla frogs, you need tadpoles in their respective biomes.

**Comment by EredmiR** [comment]
> The frog spawns like vanilla frogs, you need tadpoles in their respective biomes.

Ok, But how can I spawn the nether frogs? Thanks for the help hehe!

**Comment by EredmiR** [comment]
Ok, now I get it. But, how can I spawn the nether frogs? Thanks for the help!

**Comment by frikinjay** [comment]
Place the tadpole in lava in the nether.
