### ISSUE TITLE
Drops not working on servers, only singleplayer

### ISSUE THREAD

**Issue by DayTheMagpie** [frikinjay/morefrogs#14]
Version: Fabric 1.19.x-1.2.3b

When frogs like the Dusk and Dawn frog eat slimes on a multiplayer server, they only drop slime balls. Magma cubes drop nothing. When playing on the same instance in singleplayer, the Skybox drops as intended. The same issue persists for all frogs, including ones that drop vanilla items.

**Comment by frikinjay** [comment]
Can i get a list of the mods youre running more frogs along with?

**Comment by frikinjay** [comment]
Hopefully fixed in 1.2.5
