### ISSUE TITLE
Slime Drops Removed from Game

### ISSUE THREAD

**Issue by PastellePixie** [frikinjay/morefrogs#15]
Fabric 1.19.3 Server. Slimes do not drop slime balls upon death.

06.01 21:06:05 [Server] main/ERROR Couldn't parse loot table minecraft:entities/slime
06.01 21:06:05 [Server] INFO com.google.gson.JsonParseException: Unknown registry key in ResourceKey[minecraft:root / minecraft:frog_variant]: morefrogs:lush_warden
06.01 21:06:05 [Server] INFO at net.minecraft.class_156.method_47526(class_156.java:981) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_7380.method_43115(class_7380.java:42) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_7376.method_43097(class_7376.java:114) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_2048.method_8913(class_2048.java:169) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_2022.method_8846(class_2022.java:104) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_190$class_191.method_839(class_190.java:53) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_190$class_191.method_517(class_190.java:45) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_79$class_5337.method_29319(class_79.java:85) ~[server-intermediary.jar:?]
06.01 21:06:05 [Server] INFO at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_3518.method_15272(class_3518.java:463) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_52$class_54.method_340(class_52.java:217) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_52$class_54.deserialize(class_52.java:213) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
06.01 21:06:06 [Server] INFO at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
06.01 21:06:06 [Server] INFO at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]

**Comment by frikinjay** [comment]
Fixed in 1.2.4a fabric release.

New release is 1.2.5.
