### ISSUE TITLE
Not 1.20

### ISSUE THREAD

**Issue by cnmhqwerty** [frikinjay/morefrogs#20]
Marked on modrinth as 1.20 - 1.20.1 but when loaded in 1.20 listed as incompatible
"Replace mod 'More Frogs' (morefrogs) 1.20.1-1.2.5-fabric with any version that is compatible with: minecraft 1.20"

**Comment by frikinjay** [comment]
Sorry I've decided to skip 1.20 as its not really a relevant version and most people have already switched to 1.20.1
