### ISSUE TITLE
Arrows cause crashes

### ISSUE THREAD

**Issue by jiahuli** [frikinjay/morefrogs#6]
After installing this mod, when the shot arrow hits a surviving player or creature, it will cause the archive to crash and cannot enter
Tried fabric and Quilt have this problem
Here I provide my [modpack](https://drive.google.com/file/d/1Hj7q0HpABN2jgIY6eJHSBw62N4dsSsFY/view?usp=sharing) (MultiMC) to try
The second archive after importing into MultiMC is a problem archive

**Comment by frikinjay** [comment]
I've fixed the issue, it will be in the next update.

**Comment by frikinjay** [comment]
fixed in 1.2.2
