### ISSUE TITLE
Purpur, ender, and dusk and dawn frogs not spawning

### ISSUE THREAD

**Issue by stikyscommands** [frikinjay/morefrogs#7]
Purpur, ender, and dusk and dawn frogs not spawning in forge patch 1.0.1. To replicate: Go to biome end_highlands, go to biome the_end, or go to y level 319 in the overworld and spawn a frog. The frog will have a vanilla variant. Also, the skybox and light at the end blocks cannot be found in the creative inventory or by using /give or /setblock.

**Comment by frikinjay** [comment]
Those frogs and blocks have not been ported to forge yet, I am working on making final additions to the fabric version and ones done will port the features to the forge version.
