### ISSUE TITLE
Frogs Not spawning no matter what.

### ISSUE THREAD

**Issue by Soul-Rack** [frikinjay/morefrogs#8]
Mod version: morefrogs-1.19-1.0.1-forge.jar
Forge Verison: 1.19.2 forge 43.1.25
Minecraft Verison: 19.2
I have tried to spawn in the frogs with the tadpole eggs but they don't spawn the frog type in the biome, they only spawn in the normal frog variants. I have tried to look for them naturally but they also do not spawn in that way in their biome. I've also tried this in creative mode but it doesn't work. I have tried to find spawn eggs for them but there are none so I can't do it that way either.

**Comment by frikinjay** [comment]
Strange, I will need more details on this, if youre running the mod alongside other mods I'll need the list of the mods.
